### ISSUE TITLE
Type-rate asc-desc table filter for percentages are not behaving correctly

### ISSUE THREAD

**Issue by danejo3** [bioforensics/MicroHapulator#155]
For some reason, I found that when sorting the aggregated typing-rate table by percentage, on tab 3, the table incorrectly displays a few microhaps at the top when doing the descending order.

This first table is fine.

<img width="487" alt="Screen Shot 2022-10-06 at 3 15 29 PM" src="https://user-images.githubusercontent.com/33472323/194400255-4cd7f042-1ab7-4eca-a3af-a231f8dbe0e2.png">

The next table puts some of the KKCS microchips at the top.

<img width="488" alt="Screen Shot 2022-10-06 at 3 15 38 PM" src="https://user-images.githubusercontent.com/33472323/194401957-50996261-e093-4bc3-84a4-d116b9d2859d.png">

It seems like this is a reoccurring issue for each sample column as well.

<img width="464" alt="Screen Shot 2022-10-06 at 3 27 41 PM" src="https://user-images.githubusercontent.com/33472323/194402002-57d3fb96-a9e4-487b-9e4e-4a702044e16c.png">

**Comment by danejo3** [comment]
It seems like the KKCS is behaving differently than the others.

**Comment by standage** [comment]
Ruh roh, it looks like it's doing a lexicographical sort. Not urgent @agshumate, but when you have a chance, do you want to see if these values can be sorted numerically instead of lexicographically? Or if a "sort value" (0.0-1.0) can be defined separate from the "display value"? If not, we may need to change these from percentages to real number values between 0 and 1, which lexicographical sorting should handle correctly.

**Comment by agshumate** [comment]
whoops! I fixed this on the mapping rate table but missed this one. Should be a quick fix.
